import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1000, height: 1400 } })
const errs = []
p.on('pageerror', (e) => errs.push('PAGEERROR: ' + e.message))
p.on('console', (m) => { if (m.type() === 'error') errs.push('CONSOLE: ' + m.text()) })
await p.goto('file:///Users/kevinsites/.claude/jobs/fd11aa06/tmp/rhythms-qa.html')
await p.waitForTimeout(1500)
console.log('total:', await p.locator('#total').innerText())
console.log('steps:', await p.locator('.step').count())
console.log('phases:', await p.locator('.phase').count())
await p.locator('#c1').check()
await p.locator('#c5').check()
await p.waitForTimeout(200)
console.log('after check, done =', await p.locator('#done').innerText())
await p.reload()
await p.waitForTimeout(800)
console.log('after reload, done =', await p.locator('#done').innerText())
console.log('overflow:', await p.evaluate(() => [document.body.scrollWidth, document.body.clientWidth]))
await p.screenshot({ path: '/Users/kevinsites/.claude/jobs/fd11aa06/tmp/qa-top.png' })
await p.setViewportSize({ width: 390, height: 1200 })
await p.waitForTimeout(400)
console.log('phone overflow:', await p.evaluate(() => [document.body.scrollWidth, document.body.clientWidth]))
console.log('ERRORS:', errs.length ? errs : 'none')
await b.close()
