#!/bin/sh
# Xcode Cloud — post-clone hook.
#
# Our Xcode project is GENERATED by XcodeGen (Waffled.xcodeproj is gitignored) and
# the PowerSync SDK is VENDORED with a patch (Vendor/ is gitignored). Neither is in
# the repo, so both must be materialized on the runner after the shallow clone and
# BEFORE Xcode Cloud resolves dependencies and archives.
#
# Xcode Cloud runs this because it lives in `apps/ios/ci_scripts/` — the same
# directory as Waffled.xcodeproj. The shared scheme itself IS committed (see
# apps/ios/.gitignore) because Xcode Cloud discovers schemes from the repo.
set -e

cd "$CI_PRIMARY_REPOSITORY_PATH/apps/ios"

# 1) XcodeGen — Homebrew is preinstalled on Xcode Cloud runners.
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1
brew install xcodegen

# 2) Vendor + patch the PowerSync Swift SDK (clones into ./Vendor, gitignored).
./Scripts/vendor-powersync.sh

# 3) Regenerate Waffled.xcodeproj + Waffled-Info.plist from project.yml. This
#    overwrites the committed shared scheme with an identical one — harmless.
xcodegen generate

echo "ci_post_clone: PowerSync vendored + Waffled.xcodeproj generated."
